# Generated by Django 4.2.23 on 2025-07-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_default_shift_customuser_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_operator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_supervisor",
            field=models.BooleanField(default=False),
        ),
    ]
