# Generated by Django 4.2.23 on 2025-07-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام دستگاه")),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="مکان"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین اتصال"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                ("content", models.TextField(blank=True, verbose_name="متن")),
            ],
        ),
        migrations.CreateModel(
            name="RequestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام درخواست")),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
            ],
        ),
        migrations.CreateModel(
            name="WorkGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام گروه")),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
            ],
        ),
        migrations.CreateModel(
            name="WorkShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام شیفت")),
                ("start_time", models.TimeField(verbose_name="شروع")),
                ("end_time", models.TimeField(verbose_name="پایان")),
            ],
        ),
        migrations.CreateModel(
            name="WorkUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام واحد")),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
            ],
        ),
    ]
