# Generated by Django 4.2.23 on 2025-07-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="decision_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار"),
                    ("approved", "تأیید شده"),
                    ("rejected", "رد شده"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
