# Generated by Django 4.2.23 on 2025-07-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_leaverequest_decision_at_leaverequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="editrequest",
            name="manager_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="manager_note",
            field=models.TextField(blank=True),
        ),
    ]
