# Generated by Django 4.2.23 on 2025-07-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_editrequest_manager_note_leaverequest_manager_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="log_type",
            field=models.CharField(
                choices=[("in", "ورود"), ("out", "خروج")], default="in", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="source",
            field=models.CharField(
                choices=[("self", "کاربر"), ("auto", "سیستم"), ("manager", "مدیر")],
                default="self",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="editrequest",
            name="log_type",
            field=models.CharField(
                choices=[("in", "ورود"), ("out", "خروج")], default="in", max_length=4
            ),
        ),
    ]
