# Generated by Django 4.2.23 on 2025-07-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_attendancelog_log_type_attendancelog_source_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="editrequest",
            constraint=models.UniqueConstraint(
                fields=("user", "timestamp"), name="unique_user_timestamp"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.UniqueConstraint(
                fields=("user", "start_date", "end_date"),
                name="unique_user_leave_range",
            ),
        ),
    ]
