# Generated by Django 4.2.23 on 2025-07-17 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_request_cancelled_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "شنبه"),
                            (1, "یکشنبه"),
                            (2, "دوشنبه"),
                            (3, "سه‌شنبه"),
                            (4, "چهارشنبه"),
                            (5, "پنجشنبه"),
                            (6, "جمعه"),
                        ],
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="editrequest",
            name="cancelled_by_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
