# Generated by Django 4.2.23 on 2025-07-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_weeklyholiday_editrequest_cancelled_by_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="cancelled_by_user",
            field=models.BooleanField(default=False),
        ),
    ]
