# Generated by Django 4.2.23 on 2025-07-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_policy_shift_workgroup_workunit_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=100)),
                ("timezone", models.CharField(default="Asia/Tehran", max_length=100)),
                (
                    "time_correction",
                    models.IntegerField(default=0, help_text="اصلاح زمان (دقیقه)"),
                ),
                (
                    "week_start",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="روز شروع هفته (0=شنبه)"
                    ),
                ),
            ],
        ),
    ]
